# 节假日场景配置
scenario:
  name: "holiday"
  description: "节假日特殊流量模式场景"
  
  # 不确定性配置
  uncertainty:
    level: 0.2  # 中等不确定性
    type: "gaussian"
    parameters:
      mean: 1.0
      std: 0.2
      
  # 流量配置
  traffic:
    # 基础流量模式
    baseline:
      mean: 1000
      std: 150
      
    # 趋势配置
    trend:
      enabled: false
      slope: 0.0
      
    # 季节性配置
    seasonality:
      enabled: true
      weekly_amplitude: 0.2
      monthly_amplitude: 0.1
      
    # 随机波动
    noise:
      type: "gaussian"
      std: 100
      
  # 版本影响配置
  version_impact:
    # 基础影响因子
    base_factor: 1.2
    uncertainty: 0.2
    
    # 影响持续时间
    duration_days: 4
    decay_rate: 0.25
    
  # 特殊事件配置
  special_events:
    enabled: true
    probability: 0.05  # 5%概率出现特殊事件
    events:
      - type: "holiday_promotion"
        impact_factor: 1.5
        duration: 7
      - type: "system_maintenance"
        impact_factor: 0.3
        duration: 2
        
  # 节假日配置
  holidays:
    enabled: true
    impact_factor: 0.4  # 节假日流量降低60%
    
    # 节假日类型配置
    holiday_types:
      - type: "national_holiday"
        impact_factor: 0.3
        duration: 3
      - type: "festival"
        impact_factor: 0.5
        duration: 5
      - type: "long_weekend"
        impact_factor: 0.6
        duration: 4
        
  # 周末配置
  weekends:
    enabled: true
    impact_factor: 0.7  # 周末流量降低30%
    
  # 节假日前后流量模式
  holiday_patterns:
    pre_holiday:
      days_before: 2
      impact_factor: 1.3  # 节假日前流量增加30%
      
    post_holiday:
      days_after: 3
      impact_factor: 1.2  # 节假日后流量增加20%