# 评估配置
evaluation:
  # 基础评估设置
  basic:
    n_eval_episodes: 100
    deterministic: true
    render: false
    
  # 多场景评估配置
  multi_scenario:
    enabled: true
    scenario_types: ["normal", "extreme", "holiday"]
    scenarios_per_type: 50
    
  # 稳健性评估配置
  robustness:
    enabled: true
    metrics:
      - "mean_variance"
      - "worst_case_variance"
      - "value_at_risk"
      - "conditional_value_at_risk"
      
    # VaR和CVaR配置
    risk_metrics:
      confidence_levels: [0.95, 0.99]
      var_method: "historical"  # "historical", "parametric", "monte_carlo"
      
  # 基准比较配置
  baselines:
    enabled: true
    methods:
      - "random"
      - "greedy"
      - "genetic_algorithm"
      - "human_expert"
      
    # 遗传算法基准配置
    genetic_algorithm:
      population_size: 100
      generations: 50
      mutation_rate: 0.1
      crossover_rate: 0.8
      
  # 性能指标配置
  metrics:
    # 流量相关指标
    traffic:
      - "mean_traffic"
      - "traffic_variance"
      - "max_traffic"
      - "min_traffic"
      - "traffic_smoothness"
      
    # 发布相关指标
    release:
      - "release_count"
      - "release_frequency"
      - "rule_violations"
      - "invalid_attempts"
      
    # 稳健性指标
    robustness:
      - "mean_variance"
      - "worst_case_variance"
      - "variance_ratio"
      - "stability_index"
      
  # 可视化配置
  visualization:
    enabled: true
    output_dir: "results/evaluation"
    
    # 图表类型
    charts:
      - "traffic_comparison"
      - "release_calendar_comparison"
      - "robustness_analysis"
      - "performance_radar"
      - "learning_curves"
      
    # 导出格式
    export_formats: ["png", "svg", "html"]
    
  # 报告生成配置
  reporting:
    enabled: true
    output_dir: "results/reports"
    formats: ["html", "pdf", "json"]
    
    # 报告内容
    sections:
      - "executive_summary"
      - "performance_metrics"
      - "robustness_analysis"
      - "baseline_comparison"
      - "recommendations"
      - "appendix"